dofile("config.lua")
print("Init Servos")
_motion = require("motion_control")
_motion.init(SERVO_LEFT_PIN,SERVO_RIGHT_PIN)

print("Init Sensors")
_sensor = require("sensors")
_sensor.init(SDA_PIN, SCL_PIN)

print("Init Sumo control")
_sumo = require("sumo_control")
_sumo.init(_motion, _sensor)

DEBUG=1
_sensor.trig(LEFT_BUTTON,function() 
    print("LEFT BUTTON")
end)
_sensor.trig(RIGHT_BUTTON,function() 
    print("RIGHT BUTTON")
end)
_sensor.trig(LEFT_EDGE,function() 
    print("LEFT EDGE")
end)
_sensor.trig(RIGHT_EDGE,function() 
    print("RIGHT EGDE")
end)
_sensor.trig(BACK_EDGE,function() 
    print("BACK EDGE")
end)
_sensor.start()